# Generated by Django 4.0.3 on 2022-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_coursestudent_remove_student_course_student_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='basic.CourseStudent', to='basic.student'),
        ),
    ]
